stages:
- check
- build

lint:
  stage: check
  image: golang:1.17.9
  script:
  - go fmt .

audit:
  stage: check
  image: golang:1.17.9
  script:
  - go vet .

build:
  stage: build
  image: golang:1.17.9
  script:
  - go build -o hello .
