kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: voting-app
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  #podSubnet: "10.42.0.0/16"
  #serviceSubnet: "10.96.0.0/12"
  #kubeProxyMode: "ipvs"
#containerdConfigPatches:
#- |-
#  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
#    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraMounts:
  #- hostPath: ./audit-policy.yaml
  #  containerPath: /etc/kubernetes/audit-policy.yaml
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/nicholas/.docker/config.json
  #runtimeConfig:
  #  auditPolicyFile: /etc/kubernetes/audit-policy.yaml
  #  auditLogPath: "-"
- role: worker
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/nicholas/.docker/config.json
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "dille.io/type=lb"
- role: worker
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/nicholas/.docker/config.json
