apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: gotk-system
  namespace: gotk-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gotk-system
  url: ssh://git@github.com/nicholasdille/container-slides
status: {}
