stages:
- check
- build
- test
- deploy

default:
  image: golang:1.17.9

lint:
  stage: check
  script:
  - go fmt .

audit:
  stage: check
  script:
  - go vet .

build:
  stage: build
  script:
  - |
    go build \
        -ldflags "-X main.Version=${CI_COMMIT_REF_NAME} -X main.Author=${AUTHOR}" \
        -o hello \
        .
  artifacts:
    paths:
    - hello

test:
  stage: test
  image: alpine
  script:
  - ./hello

deploy:
  stage: deploy
  environment:
    name: ${CI_COMMIT_REF_NAME}
  before_script:
  - apk update
  - apk add curl ca-certificates
  script:
  - |
    curl https://${CI_COMMIT_REF_NAME}.seat0.inmylab.de/ \
        --fail \
        --upload-file hello \
        --user admin:${PASS_LIVE}