stages:
- prepare

default:
  image: docker:dind

renovate:
  stage: prepare
  image: renovate/renovate:29.8.3
  variables:
    LOG_LEVEL: debug
  script:
  - |
    if test -z "${RENOVATE_TOKEN}"; then
        echo "[ERROR] You must add an access token in the CI variable RENOVATE_TOKEN."
        echo "        The token can be a project access token."
        exit 1
    fi
  - renovate --platform=gitlab --endpoint="${CI_API_V4_URL}" "${CI_PROJECT_PATH}"
  only:
    refs:
    - schedule
