---
apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: web
    version: "1"
spec:
  containers:
  - name: apache
    image: httpd:2.4
    ports:
    - name: web
      containerPort: 80
