# https://docs.docker.com/compose/compose-file

volumes:
  traefik_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

services:

  # https://doc.traefik.io/traefik/
  traefik:
    image: traefik:v2.6
    command:
    - --log=true
    - --log.level=DEBUG
    - --api=true
    #- --api.insecure=true
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --entrypoints.https.address=:443
    - --entrypoints.ssh.address=:2222
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    - --certificatesresolvers.le.acme.httpchallenge=true
    - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
    - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    - --certificatesresolvers.le.acme.email=workshop20220507@inmylab.de
    - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    - --certificatesresolvers.le2.acme.tlschallenge=true
    - --certificatesresolvers.le2.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    - --certificatesresolvers.le2.acme.email=workshop20220507@inmylab.de
    - --certificatesresolvers.le2.acme.storage=/letsencrypt/acme2.json
    ports:
    - 80:80
    - 443:443
    - 2222:2222
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    - traefik_data:/letsencrypt
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`traefik.172.20.57.234.nip.io`)

  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    #image: gitlab/gitlab-ee:14.10.0-ee.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.172.20.57.234.nip.io'
        gitlab_rails['initial_root_password'] = 'MySuperSecretAndSecurePass0rd!'
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    shm_size: 256m
    volumes:
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    labels:
      traefik.enable: "true"
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.entrypoints: https
      traefik.http.routers.www.rule: Host(`gitlab.172.20.57.234.nip.io`)
      traefik.http.routers.www.tls.certresolver: le
      traefik.tcp.routers.ssh.entrypoints: ssh
      traefik.tcp.routers.ssh.rule: HostSNI(`gitlab.172.20.57.234.nip.io`)
      traefik.tcp.routers.ssh.tls.passthrough: "true"
