concurrent = 1
check_interval = 0

[[runners]]
  name = "runner-1"
  url = "http://gitlab"
  executor = "docker"

  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    pull_policy = "if-not-present"
    disable_cache = false
    volumes = ["/var/run/docker/sock:/var/run/docker.sock"]
    shm_size = 0
