# https://docs.docker.com/compose/compose-file

volumes:
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true

services:

  # https://doc.traefik.io/traefik/
  traefik:
    image: traefik:v2.6
    command:
    - --log=true
    - --log.level=DEBUG
    - --api=true
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --entrypoints.ssh.address=:22
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 2222:22
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "netstat -tunapl | grep LISTEN | grep :80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: HostRegexp(`traefik.{domain:.+}`)

  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        #external_url 'http://gitlab.172.20.57.234.nip.io'
        gitlab_rails['initial_root_password'] = 'MySuperSecretAndSecurePass0rd!'

        # Prevent conflict with host SSH port
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    # https://docs.gitlab.com/ee/install/docker.html#devshm-mount-not-having-enough-space-in-docker-container
    shm_size: 256m
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    labels:
      traefik.enable: "true"
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.entrypoints: http
      traefik.http.routers.www.rule: HostRegexp(`gitlab.{domain:.+}`)
      traefik.tcp.services.ssh.loadbalancer.server.port: 22
      traefol.tcp.routers.ssh.entrypoints: ssh
      traefik.tcp.routers.ssh.rule: HostSNI(`*`)
