# https://docs.docker.com/compose/compose-file

services:

  # https://docs.gitlab.com/ee/install/docker.html
  vscode:
    image: codercom/code-server:4.3.0
    volumes:
    - ${HOME}/.config:/home/coder/.config
    - ${PWD}:/home/coder/project
    user: ${USER}
    environment:
      DOCKER_USER: ${USER}
    labels:
      traefik.enable: "true"
      traefik.http.services.vscode.loadbalancer.server.port: 8080
      traefik.http.routers.vscode.entrypoints: http
      traefik.http.routers.vscode.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`) || Host(`vscode.${IP:?You must supply IP}.nip.io`)
      traefik.http.routers.vscode.service: vscode
