# https://docs.docker.com/compose/compose-file

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgresql_data:
  redis_data:
  gitaly_config:
  gitaly_data:
  gitaly_gitlab:
  gitaly_logs:

services:

  gitlab:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'
        
        external_url 'http://gitlab.${DOMAIN:?You must supply DOMAIN}'

        # Prevent conflict with host SSH port
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        # Configure remote gitaly
        gitaly['enable'] = false
        git_data_dirs({
          'default' => { 'gitaly_address' => 'tcp://gitaly:8075' },
        })
        gitlab_rails['gitaly_token'] = "gitaly"
        
        # Configure remote postgresql
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'db'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        
        # Configure remote redis
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = 'redis'
    # https://docs.gitlab.com/ee/install/docker.html#devshm-mount-not-having-enough-space-in-docker-container
    shm_size: 256m
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    labels:
      traefik.enable: "true"
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.entrypoints: http
      traefik.http.routers.www.rule: Host(`gitlab.${DOMAIN:?You must supply DOMAIN}`) || Host(`gitlab.${IP:?You must supply IP}.nip.io`)
      traefik.tcp.services.ssh.loadbalancer.server.port: 2222
      traefik.tcp.routers.ssh.entrypoints: ssh
      traefik.tcp.routers.ssh.rule: HostSNI(`gitlab.${DOMAIN:?You must supply DOMAIN}`) || HostSNI(`gitlab.${IP:?You must supply IP}.nip.io`)

  db:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        # Disable services
        sidekiq['enable'] = false
        puma['enable'] = false
        registry['enable'] = false
        gitaly['enable'] = false
        gitlab_workhorse['enable'] = false
        nginx['enable'] = false
        prometheus_monitoring['enable'] = false
        redis['enable'] = false

        postgresql['enable'] = true
        postgresql['listen_address'] = '0.0.0.0'
        postgresql['user'] = 'gitlab'
        # password=gitlab
        # username=gitlab
        # echo -n '${password}${username}' | md5sum - | cut -d' ' -f1`
        postgresql['sql_user_password'] = 'b7a289c0600988fe8e709dd2887e4d37'
        postgresql['md5_auth_cidr_addresses'] = ['10.42.0.0/16']
        postgresql['trust_auth_cidr_addresses'] = ['10.42.0.0/16']

        ## Configure gitlab_rails
        gitlab_rails['auto_migrate'] = false

        postgres_exporter['enable'] = true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_data:/var/opt/gitlab

  redis:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        # Disable services
        alertmanager['enable'] = false
        grafana['enable'] = false
        prometheus['enable'] = false

        redis_master_role['enable'] = true
        redis['port'] = 6379
        redis['bind'] = '0.0.0.0'
        redis['password'] = 'redis'
        gitlab_rails['redis_password'] = 'redis'
        gitlab_rails['auto_migrate'] = false

        redis_exporter['listen_address'] = '0.0.0.0:9121'
        gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8','10.42.0.0/16']
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - redis_data:/var/opt/gitlab

  gitaly:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        # Disable services
        postgresql['enable'] = false
        redis['enable'] = false
        nginx['enable'] = false
        puma['enable'] = false
        sidekiq['enable'] = false
        gitlab_workhorse['enable'] = false
        alertmanager['enable'] = false
        grafana['enable'] = false
        prometheus['enable'] = false
        
        # Prevent database connections during 'gitlab-ctl reconfigure'
        gitlab_rails['rake_cache_clear'] = false
        gitlab_rails['auto_migrate'] = false
    
        gitlab_rails['internal_api_url'] = 'http://gitlab'
        gitlab_workhorse['auth_backend'] = 'http://gitlab'
    
        gitaly['listen_addr'] = "0.0.0.0:8075"
        gitaly['auth_token'] = "gitaly"
    
        gitaly['storage'] = [
          { 'name' => 'default', 'path' => '/var/opt/gitlab-data/git-data/repositories' },
        ]
        git_data_dirs({ "default" => { "path" => "/var/opt/gitlab-data/git-data" } })
        
        # monitoring
        gitaly['prometheus_listen_addr'] = "0.0.0.0:9236"
        gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8','10.42.0.0/16']
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitaly_config:/etc/gitlab
    - gitaly_data:/var/opt/gitlab-data
    - gitaly_gitlab:/var/opt/gitlab
    - gitaly_logs:/var/log/gitlab
