---
apiVersion: v1
kind: Pod
metadata:
  name: volume-configmap
  labels:
    app: volume-configmap
spec:
  volumes:
  - name: data
    configMap:
      name: pages
  containers:
  - name: configmap
    image: nginx:mainline-alpine
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
