---
apiVersion: v1
kind: Pod
metadata:
  name: volume-hostpath
spec:
  volumes:
  - name: data
    hostPath:
      path: /data
      type: DirectoryOrCreate
  containers:
  - name: hostpath
    image: nicholasdille/sleeper
    volumeMounts:
    - mountPath: /data
      name: data
