apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    app: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns
          args:
            - --source crd
            - --crd-source-apiversion externaldns.k8s.io/v1alpha1
            - --crd-source-kind DNSEndpoint
            - --provider inmemory
