---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-impersonator
rules:
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "users"
  - "groups"
  verbs:
  - "impersonate"
  resourceNames:
  - "system:serviceaccount:default:cluster-admin"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: cluster-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-impersonator
subjects:
- kind: ServiceAccount
  name: cluster-reader
  namespace: default
