---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader
  namespace: test
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-impersonator
rules:
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "users"
  - "groups"
  verbs:
  - "impersonate"
  resourceNames:
  - "system:serviceaccounts:test:admin"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reader
subjects:
- kind: ServiceAccount
  name: reader
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-impersonator
subjects:
- kind: ServiceAccount
  name: reader
  namespace: test
