apiVersion: v1
kind: Pod
metadata:
  name: buildkitd
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
    container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
spec:
  containers:
  - name: buildkitd
    image: moby/buildkit:master-rootless
    args:
    - --oci-worker-no-process-sandbox
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    readinessProbe:
      exec:
        command:
        - buildctl
        - debug
        - workers
      initialDelaySeconds: 5
      periodSeconds: 30
    livenessProbe:
      exec:
        command:
        - buildctl
        - debug
        - workers
      initialDelaySeconds: 5
      periodSeconds: 30