docker-build:
  image: docker:20.10.16
  stage: build

  services:
  - name: docker:20.10.16-dind
    command:
    - dockerd
    - --host
    - tcp://0.0.0.0:2375

  script:
  - docker build --pull .

