---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: podinfo
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller
  fetch:
  - git:
      url: https://github.com/nicholasdille/container-slides
      ref: origin/master
      subPath: 140_gitops/apps/podinfo
  template:
  - ytt: {}
  deploy:
  - kapp: {}
