---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
# Spezifikation des Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nicholasdille/nginx-hello:1.18
