stages:
- check
- build
- test
- trigger

default:
  image: golang:1.17.9

lint:
  stage: check
  script:
  - go fmt .

audit:
  stage: check
  script:
  - go vet .

build:
  stage: build
  script:
  - |
    go build \
        -ldflags "-X main.Version=${CI_COMMIT_REF_NAME} -X main.Author=${AUTHOR}" \
        -o hello \
        .
  artifacts:
    paths:
    - hello

test:
  stage: test
  image: alpine
  script:
  - ./hello

trigger:
  script: |
    curl https://gitlab.seatN.inmylab.de/api/v4/projects/<PROJECT_ID>/trigger/pipeline \
        --request POST \
        --fail \
        -F token=<TOKEN> \
        -F ref=<BRANCH>
